## ================================================================
## Myeloid cell downstream analysis
## ================================================================
##
## This script performs downstream analyses of myeloid cells in glioma,
## including myeloid subcluster visualization, cell proportion analysis,
## Ro/e enrichment analysis, BayesPrism-based bulk RNA-seq deconvolution,
## survival analysis, AUCell-based subtype-related gene-set scoring, and
## Monocle2 pseudotime analysis for monocytes/macrophages and microglia.
##
## -------------------------
## Required input files
## -------------------------
##
## 1. Myeloid.rds
##    A processed Seurat object containing annotated myeloid cells.
##    Required metadata columns include:
##      - celltype
##      - group
##      - tumor_type
##    The RNA assay should contain raw count data.
##
## 2. signature.xlsx
##    An Excel file containing subtype-related gene signatures.
##    Required columns include:
##      - IDHWT
##      - IDHMU
##      - Noncodel
##      - Codel
##
## 3. TCGAGBMLGG全数据.xlsx
##    A processed TCGA GBM/LGG bulk RNA-seq expression matrix with
##    survival information. The file should contain overall survival
##    time, survival status, and gene expression values for each sample.
##
## -------------------------
## Main output files
## -------------------------
##
## 1. BayesPrism-inferred myeloid fraction.csv
##    BayesPrism-inferred myeloid subcluster fractions for TCGA GBM/LGG
##    bulk RNA-seq samples, combined with survival metadata.
##
## 2. survival/
##    A folder containing Kaplan-Meier survival plots for each
##    BayesPrism-inferred myeloid subcluster fraction.
##
## 3. TAMacro_GBM_monocle_cds.rds
##    Monocle2 CellDataSet object for monocytes/macrophages in GBM.
##
## 4. TAMacro_AC_monocle_cds.rds
##    Monocle2 CellDataSet object for monocytes/macrophages in astrocytoma.
##
## 5. TAMacro_OD_monocle_cds.rds
##    Monocle2 CellDataSet object for monocytes/macrophages in oligodendroglioma.
##
## 6. MG_GBM_monocle_cds.rds
##    Monocle2 CellDataSet object for microglia in GBM.
##    Microglia cells were downsampled before Monocle2 analysis to ensure
##    computational feasibility.
##
## 7. MG_AC_monocle_cds.rds
##    Monocle2 CellDataSet object for microglia in astrocytoma.
##
## 8. MG_OD_monocle_cds.rds
##    Monocle2 CellDataSet object for microglia in oligodendroglioma.
##
## -------------------------
## Main analyses generated by this script
## -------------------------
##
## 1. Myeloid subcluster visualization.
## 2. Myeloid subcluster proportion analysis across glioma molecular groups.
## 3. Ro/e enrichment analysis of myeloid subclusters across glioma molecular groups.
## 4. BayesPrism-based deconvolution of myeloid subcluster fractions in bulk RNA-seq data.
## 5. Survival analysis based on inferred myeloid subcluster fractions.
## 6. AUCell scoring of subtype-related gene signatures in myeloid cells.
## 7. Monocle2 pseudotime analysis of monocytes/macrophages.
## 8. Monocle2 pseudotime analysis of microglia.
## 9. Pseudotime-associated subtype-related gene-set score visualization.
## ================================================================

library(Seurat)
library(Startrac)
library(RColorBrewer)
library(pheatmap)
library(ggplot2)
library(dplyr)
library(openxlsx)
library(tibble)

Myeloid <- readRDS("Myeloid.rds")

cell_colors <- c(
  "MΦ-Resi"           =   "#67a8cd",
  "MG-Activation"     =   "#A6C990",
  "MG-Homeo"          =   "#A6CEE3",
  "MG-IFN"            =   "#a6542c",
  "MG-Inflam"         =   "#FDBF6F",
  "MG-Lipid"          =   "#66c2a5",
  "MO-Inflam"         =   "#cf9f88",
  "Prolif"            =   "#e78ac3",
  "Neutrophil"        =   "#17BECF",
  "MΦ-Hypoxic"        =   "#B3E2D5", 
  "MΦ-Inflam"         =   "#e63836",
  "DC-cDC2"           =   "#EEBDD1",
  "MΦ-Metal"          =   "#E4CEBB",
  "MO-Rest"           =   "#8552a1"
)
Myeloid$tumor_type <- factor(
  Myeloid$tumor_type,
  levels = c("WT", "M-N", "M-C")
)

##--Fig7A---------------------------------------------##

p <- DimPlot(Myeloid, reduction = "tsne",label=T,cols = cell_colors)

##--Fig7B----- cell proportion----------------------------##
meta.data <- Myeloid@meta.data

meta.data$celltype <- factor(
  meta.data$celltype,
  levels = c(
    "MG-Activation",
    "MG-Homeo",
    "MG-IFN",
    "MG-Inflam",
    "MG-Lipid",
    "MO-Inflam",
    "MO-Rest",
    "MΦ-Hypoxic",
    "MΦ-Inflam",
    "MΦ-Metal",
    "MΦ-Resi",
    "DC-cDC2",
    "Neutrophil",
    "Prolif"
  )
)

meta.data$tumor_type <- factor(
  meta.data$tumor_type,
  levels = c("WT", "M-N", "M-C")
)

sub_data <- table(meta.data$tumor_type, meta.data$celltype) %>% 
  as.data.frame() %>% 
  group_by(Var1) %>% 
  mutate(
    cell_proportion = Freq/sum(Freq)
  )
colnames(sub_data) <- c("sample", "cluster", "cell_num", "cell_proportion")

p <- ggplot(sub_data)+
  geom_col(aes(x = sample, y = cell_proportion, fill = cluster), position = 'stack', width = 0.6)+
  theme_bw()+
  theme(
    panel.background = element_blank(),
    axis.text.x = element_text(
      angle = 90
    )
  )+scale_fill_manual(values = cell_colors)


##-Fig7C-------------Roe Score-----------------------------##
Roe <- calTissueDist(meta.data,
                     colname.cluster = "celltype", 
                     colname.tissue = "tumor_type", 
                     method = "chisq", 
                     min.rowSum = 0) 
colours  <- colorRampPalette(brewer.pal(9, "OrRd"))(50)

ph  <- pheatmap(Roe,
                border_color = "black",
                color = colours,
                scale = 'none',
                fontsize_row = 12,
                fontsize_col = 6,
                #angle_col = 45,
                drop_levels=F,
                show_rownames = T,
                show_colnames = T,
                cluster_cols = F,
                cluster_rows = F,
                display_numbers = TRUE,
                cellwidth = 20, 
                cellheight = 20
                
)


##--------------------------------------------------------------------------##

##Fig7D--------Bulk RNA-seq deconvolution using BayesPrism------------------##

##---------------------------------------------------------------------------##
library(BayesPrism)
library(survival)
library(survminer)
species = "hs"  
sc.dat <-  as.matrix(t(GetAssayData(Myeloid, assay = "RNA", slot = "counts")))
cell.type.labels<-Myeloid@meta.data$celltype  
cell.state.labels<-NULL   

#1,QC of cell type and state labels
plot.cor.phi (input=sc.dat, 
              input.labels=cell.type.labels, 
              title="cell type correlation",
              cexRow=0.5, cexCol=0.5
)

#2,Filter outlier genes
sc.stat <- plot.scRNA.outlier(
  input=sc.dat, 
  cell.type.labels=cell.type.labels,
  species=species, 
  return.raw=TRUE 
)

sc.dat.filtered <- cleanup.genes (input=sc.dat,
                                  input.type="count.matrix",
                                  species=species, 
                                  gene.group=c( "Rb","Mrp","other_Rb","chrM","MALAT1","chrX","chrY") ,
                                  exp.cells=5)

sc.dat.filtered.pc <-  select.gene.type (sc.dat.filtered,
                                         gene.type = "protein_coding")

exp <- read.xlsx("TCGAGBMLGG全数据.xlsx")
rownames(exp) <- exp[,1]
exp <- exp[,-1]
exp <- as.data.frame(t(exp))

metadata <- exp[,c(4:5)]
names(metadata) <- c("OS.time","OS")
metadata$OS     <- as.numeric (metadata$OS)
metadata$OS.time <- as.numeric (metadata$OS.time)


n <- ncol(exp)
exp<- exp[,c(13:n)]
exp <- as.data.frame(t(exp))
Symbol <- rownames(exp)
Sample  <- names(exp)
exp <- as.data.frame(lapply(exp,as.numeric))
rownames(exp) <- Symbol

bk.dat<-as.matrix(t(exp))

bk.stat <- plot.bulk.outlier(
  bulk.input=bk.dat,
  sc.input=sc.dat, 
  cell.type.labels=cell.type.labels,
  species=species,
  return.raw=TRUE
)

plot.bulk.vs.sc (sc.input = sc.dat.filtered,
                 bulk.input = bk.dat
)

myPrism <- new.prism(
  reference=sc.dat.filtered.pc, 
  mixture=bk.dat,
  input.type="count.matrix", 
  cell.type.labels = cell.type.labels, 
  cell.state.labels = NULL,
  key=NULL,
  outlier.cut=0.01,
  outlier.fraction=0.1)

bp.res <- run.prism(prism = myPrism, n.cores=20)

score <- get.fraction(bp=bp.res,
                      which.theta="final",
                      state.or.type="type")
score <- as.data.frame(score)
score <- rownames_to_column(score, "id")

metadata <- rownames_to_column(metadata, "id")
metadata_score <-left_join(metadata,score,by="id")
write.csv(metadata_score,"BayesPrism-inferred myeloid fraction.csv",row.names = F)


dir.create("survival", showWarnings = FALSE)
for (i in colnames(metadata_score)[4:ncol(metadata_score)]) {
  
  rt <- metadata_score
  med <- median(rt[[i]], na.rm = TRUE)
  rt$group <- ifelse(rt[[i]] > med, "High", "Low")
  rt$group <- factor(rt$group, levels = c("High", "Low"))
  diff <- survdiff(Surv(OS.time, OS) ~ group, data = rt)
  p <- 1 - pchisq(diff$chisq, df = 1)
  
  if (p < 0.0001) {
    pValue <- "p < 0.0001"
  } else {
    pValue <- paste0("p = ", sprintf("%.4f", p))
  }
  
  fit <- survfit(Surv(OS.time, OS) ~ group, data = rt)
  surPlot <- ggsurvplot(
    fit,
    data = rt,
    pval = pValue,
    risk.table = FALSE,
    ggtheme = theme_classic() +
      theme(
        axis.text = element_text(color = "black", size = 7),
        axis.title = element_text(color = "black"),
        panel.grid = element_blank()
      ),
    censor.shape = 124,
    censor.size = 2,
    conf.int = FALSE,
    legend.labs = c("High", "Low"),
    legend.title = i,
    xlab = "Overall survival (months)",
    ylab = "Survival probability",
    palette = c("#E31A1C", "#1F78B4")
  )
  pdf(
    paste0("survival/", i, ".pdf"),
    onefile = FALSE,
    width = 5.5,
    height = 5
  )
  print(surPlot)
  dev.off()
}


##--------------------------------------------------------------------------##

##Fig7E---------------------179,68,30,83 gene score----------------------##

##---------------------------------------------------------------------------##

library(AUCell)
library(Matrix)
library(ggplot2)
library(scales)

signature  <- read.xlsx("signature.xlsx",1)

gene_179<- na.omit(signature$IDHWT)
gene_68 <- na.omit(signature$IDHMU)
gene_30 <- na.omit(signature$Noncodel)
gene_83 <- na.omit(signature$Codel)


expr <- GetAssayData(Myeloid, assay = "RNA", slot = "counts")
gene_sets <- list(
  gene_179 = gene_179,   
  gene_68  = gene_68,
  gene_30  = gene_30,
  gene_83  = gene_83
)

cells_AUC <- AUCell_run(expr, gene_sets)
auc_mat <- t(getAUC(cells_AUC))[colnames(Myeloid), ]
Myeloid@meta.data <- cbind(Myeloid@meta.data, auc_mat)

##The drawing code is already available in "04_Fig3F_Fig3G_Fig4H_Fig4I_Gene set score.R"

##--------------------------------------------------------------------------##

##Fig7F,G,H,I,J,K------ GBM,Astrocytoma,Oligodendroglioma--monocle-----------------##

##---------------------------------------------------------------------------##
library(monocle)
library(ggplot2)
library(AUCell)     
library(openxlsx)
library(dplyr)
library(ggridges)


TAMacro <- subset( Myeloid,
                   subset = celltype %in% c(
                     "MO-Inflam",
                     "MO-Rest",
                     "MΦ-Hypoxic",
                     "MΦ-Inflam",
                     "MΦ-Metal",
                     "MΦ-Resi"
                   )
)

TAMacro$celltype <- factor(
  TAMacro$celltype,
  levels = c(
    "MO-Inflam",
    "MO-Rest",
    "MΦ-Hypoxic",
    "MΦ-Inflam",
    "MΦ-Metal",
    "MΦ-Resi"
  )
)

TAMacro_GBM <- subset(TAMacro, group == "GBM")

data <- GetAssayData(TAMacro_GBM, assay = "RNA", slot = "counts")
data <- as(as.matrix(data),'sparseMatrix')


pd <- new('AnnotatedDataFrame', data = TAMacro_GBM@meta.data)
fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
fd <- new('AnnotatedDataFrame', data = fData)

HSMM <- newCellDataSet(data,
                       phenoData = pd,
                       featureData = fd,
                       expressionFamily = negbinomial.size())
HSMM <- estimateSizeFactors(HSMM)
HSMM <- estimateDispersions(HSMM,cores=30)
HSMM <- detectGenes(HSMM, min_expr = 0.1 )
print(head(fData(HSMM)))

expressed_genes <- row.names(subset(fData(HSMM),
                                    num_cells_expressed >= 10))
head(pData(HSMM))


mito_genes <- grep("^MT-", rownames(HSMM), value = TRUE)
ribo_genes <- grep("^RPS|^RPL", rownames(HSMM), value = TRUE)
candidate <- setdiff(expressed_genes, c(mito_genes, ribo_genes))


diff_test_res <- differentialGeneTest(HSMM[candidate,],       
                                      fullModelFormulaStr = "~ celltype",
                                      cores = 30)

ordering_genes <- subset(diff_test_res, qval < 0.01)
ordering_genes <- ordering_genes[order(ordering_genes$qval),]

ordering_genes <- rownames(ordering_genes)[1:1000]


HSMM <- setOrderingFilter(HSMM, ordering_genes)
plot_ordering_genes(HSMM)
HSMM <- reduceDimension(HSMM, max_components = 2,
                        method = 'DDRTree')
HSMM <- orderCells(HSMM)


table(pData(HSMM)$State,pData(HSMM)$celltype)     

cds <- orderCells(HSMM, root_state = 3) 


TAMacro_GBM$Pseudotime <- Biobase::pData(cds)[colnames(TAMacro_GBM), "Pseudotime"]

p <- plot_cell_trajectory(cds,color_by="Pseudotime") 

signature <- read.xlsx("signature.xlsx",1)
IDHWT     <-  na.omit(signature$IDHWT)

##AUC Score
exprMatrix <-  GetAssayData(TAMacro_GBM, assay = "RNA", slot = "counts")
cells_AUC2 <-  AUCell_run(exprMatrix, IDHWT)
AUCell_auc <-  cells_AUC2@assays@data@listData[["AUC"]]
TAMacro_GBM$AUC <- AUCell_auc
common_cells <- intersect(
  rownames(pData(cds)),
  colnames(TAMacro_GBM)
)
Biobase::pData(cds)[common_cells, "AUC"] <- TAMacro_GBM$AUC[common_cells]


##179-gene signature score along pseudotime
df <- data.frame(
  cell = rownames(Biobase::pData(cds)),
  pseudotime = Biobase::pData(cds)$Pseudotime,
  AUC = Biobase::pData(cds)$AUC,
  celltype = Biobase::pData(cds)$celltype
)


##Fig.7G(G-1)
p <- ggplot(df, aes(x = pseudotime, y = AUC)) +
  geom_point(aes(color = celltype), alpha = 0.9, size = 1)+ 
  geom_smooth(aes(group = 1), method = "loess", se = FALSE, color = "blue", size = 1) +
  scale_color_manual(values = cell_colors) +
  theme_minimal(base_size = 14) +
  theme(
    panel.border = element_rect(color = "black", fill = NA, size = 1), 
    panel.background = element_blank(),  
    plot.background = element_blank(),
    axis.ticks = element_line(color = "black", size = 0.5), 
    axis.ticks.length = unit(0.2, "cm")
  ) +labs(
    title = "179 Gene Score",
    x = "Pseudotime",
    y = "179 Gene Score",
    color = "celltype"
  )

##Fig.7F(F-1)
df <- data.frame(
  pseudotime = pData(cds)$Pseudotime,
  celltype = pData(cds)$celltype
)

p <- ggplot(df, aes(x = pseudotime, y = celltype, fill = celltype)) +
  geom_density_ridges(scale = 1.5, alpha = 0.9, color = "white") +
  scale_fill_manual(values = cell_colors) +
  labs(x = "Pseudotime", y = "celltype", title = "") +
  theme_bw(base_size = 14) +
  theme(
    legend.position = "none",
    panel.border = element_rect(color = "black", fill = NA, size = 1),  
    panel.grid.major = element_blank(),  
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.5)  
  )


##Fig.7H(H-1)
## Monocle trajectory colored by 179-gene AUC score
p <-  plot_cell_trajectory(cds, color_by = "AUC") +
  scale_color_viridis_c() +
  ggtitle("179gene score")

saveRDS(cds,"TAMacro_GBM_monocle_cds.rds") 




##-------------------02MO and MO: Astrocytoma-------------------------##
TAMacro_Astro <- subset(TAMacro, group == "Astrocytoma")

data <- GetAssayData(TAMacro_Astro, assay = "RNA", slot = "counts")
data <- as(as.matrix(data),'sparseMatrix')


pd <- new('AnnotatedDataFrame', data = TAMacro_Astro@meta.data)
fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
fd <- new('AnnotatedDataFrame', data = fData)

HSMM <- newCellDataSet(data,
                       phenoData = pd,
                       featureData = fd,
                       expressionFamily = negbinomial.size())
HSMM <- estimateSizeFactors(HSMM)
HSMM <- estimateDispersions(HSMM,cores=30)
HSMM <- detectGenes(HSMM, min_expr = 0.1 )
print(head(fData(HSMM)))

expressed_genes <- row.names(subset(fData(HSMM),
                                    num_cells_expressed >= 10))
head(pData(HSMM))


mito_genes <- grep("^MT-", rownames(HSMM), value = TRUE)
ribo_genes <- grep("^RPS|^RPL", rownames(HSMM), value = TRUE)
candidate <- setdiff(expressed_genes, c(mito_genes, ribo_genes))



diff_test_res <- differentialGeneTest(HSMM[candidate,],       
                                      fullModelFormulaStr = "~ celltype",
                                      cores = 30)

ordering_genes <- subset(diff_test_res, qval < 0.01)
ordering_genes <- ordering_genes[order(ordering_genes$qval),]

ordering_genes <- rownames(ordering_genes)[1:1000]


HSMM <- setOrderingFilter(HSMM, ordering_genes)
plot_ordering_genes(HSMM)
HSMM <- reduceDimension(HSMM, max_components = 2,
                        method = 'DDRTree')
HSMM <- orderCells(HSMM)

table(pData(HSMM)$State,pData(HSMM)$celltype)     

cds <- orderCells(HSMM, root_state = 2) 


TAMacro_Astro$Pseudotime <- 
  Biobase::pData(cds)[colnames(TAMacro_Astro), "Pseudotime"]

p <- plot_cell_trajectory(cds,color_by="Pseudotime") 

signature <- read.xlsx("signature.xlsx",1)
Noncodel    <-  na.omit(signature$Noncodel)

##AUC Score
exprMatrix <-  GetAssayData(TAMacro_Astro, assay = "RNA", slot = "counts")
cells_AUC2 <-  AUCell_run(exprMatrix, Noncodel)
AUCell_auc <-  cells_AUC2@assays@data@listData[["AUC"]]
TAMacro_Astro$AUC <- AUCell_auc
common_cells <- intersect(
  rownames(pData(cds)),
  colnames(TAMacro_Astro)
)
Biobase::pData(cds)[common_cells, "AUC"] <- TAMacro_Astro$AUC[common_cells]


##30-gene signature score along pseudotime
df <- data.frame(
  cell = rownames(Biobase::pData(cds)),
  pseudotime = Biobase::pData(cds)$Pseudotime,
  AUC = Biobase::pData(cds)$AUC,
  celltype = Biobase::pData(cds)$celltype
)


##Fig.7G(G-2)
p <- ggplot(df, aes(x = pseudotime, y = AUC)) +
  geom_point(aes(color = celltype), alpha = 0.9, size = 1)+ 
  geom_smooth(aes(group = 1), method = "loess", se = FALSE, color = "blue", size = 1) +
  scale_color_manual(values = cell_colors) +
  theme_minimal(base_size = 14) +
  theme(
    panel.border = element_rect(color = "black", fill = NA, size = 1), 
    panel.background = element_blank(),  
    plot.background = element_blank(),
    axis.ticks = element_line(color = "black", size = 0.5), 
    axis.ticks.length = unit(0.2, "cm")
  ) +labs(
    title = "30 Gene Score",
    x = "Pseudotime",
    y = "30 Gene Score",
    color = "celltype"
  )

##Fig.7F(F-2)
df <- data.frame(
  pseudotime = pData(cds)$Pseudotime,
  celltype = pData(cds)$celltype
)

p <- ggplot(df, aes(x = pseudotime, y = celltype, fill = celltype)) +
  geom_density_ridges(scale = 1.5, alpha = 0.9, color = "white") +
  scale_fill_manual(values = cell_colors) +
  labs(x = "Pseudotime", y = "celltype", title = "") +
  theme_bw(base_size = 14) +  # 白背景
  theme(
    legend.position = "none",
    panel.border = element_rect(color = "black", fill = NA, size = 1),  
    panel.grid.major = element_blank(),  
    panel.grid.minor = element_blank(),  
    plot.title = element_text(hjust = 0.5)  
  )


##Fig.7H(H-2)
## Monocle trajectory colored by 30-gene AUC score
p <-  plot_cell_trajectory(cds, color_by = "AUC") +
  scale_color_viridis_c() +
  ggtitle("30gene score")


saveRDS(cds,"TAMacro_AC_monocle_cds.rds") 



##-------------------03 MO and MO: Oligodendroglioma ---------------------##
TAMacro_OD <- subset(TAMacro, group == "Oligodendroglioma")

data <- GetAssayData(TAMacro_OD, assay = "RNA", slot = "counts")
data <- as(as.matrix(data),'sparseMatrix')


pd <- new('AnnotatedDataFrame', data = TAMacro_OD@meta.data)
fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
fd <- new('AnnotatedDataFrame', data = fData)

HSMM <- newCellDataSet(data,
                       phenoData = pd,
                       featureData = fd,
                       expressionFamily = negbinomial.size())
HSMM <- estimateSizeFactors(HSMM)
HSMM <- estimateDispersions(HSMM,cores=30)
HSMM <- detectGenes(HSMM, min_expr = 0.1 )
print(head(fData(HSMM)))

expressed_genes <- row.names(subset(fData(HSMM),
                                    num_cells_expressed >= 10))
head(pData(HSMM))


mito_genes <- grep("^MT-", rownames(HSMM), value = TRUE)
ribo_genes <- grep("^RPS|^RPL", rownames(HSMM), value = TRUE)
candidate <- setdiff(expressed_genes, c(mito_genes, ribo_genes))



diff_test_res <- differentialGeneTest(HSMM[candidate,],       
                                      fullModelFormulaStr = "~ celltype",
                                      cores = 30)

ordering_genes <- subset(diff_test_res, qval < 0.01)
ordering_genes <- ordering_genes[order(ordering_genes$qval),]
ordering_genes <- rownames(ordering_genes)[1:1000]


HSMM <- setOrderingFilter(HSMM, ordering_genes)
plot_ordering_genes(HSMM)
HSMM <- reduceDimension(HSMM, max_components = 2,
                        method = 'DDRTree')
HSMM <- orderCells(HSMM)

table(pData(HSMM)$State,pData(HSMM)$celltype)     

cds <- orderCells(HSMM, root_state = 1) 

TAMacro_OD$Pseudotime <- 
  Biobase::pData(cds)[colnames(TAMacro_OD), "Pseudotime"]

p <- plot_cell_trajectory(cds,color_by="Pseudotime") 

signature <- read.xlsx("signature.xlsx",1)
Codel     <-  na.omit(signature$Codel)

##AUC Score
exprMatrix <-  GetAssayData(TAMacro_OD, assay = "RNA", slot = "counts")
cells_AUC2 <-  AUCell_run(exprMatrix, Codel)
AUCell_auc <-  cells_AUC2@assays@data@listData[["AUC"]]
TAMacro_OD$AUC <- AUCell_auc
common_cells <- intersect(
  rownames(pData(cds)),
  colnames(TAMacro_OD)
)
Biobase::pData(cds)[common_cells, "AUC"] <- TAMacro_OD$AUC[common_cells]


##83-gene signature score along pseudotime
df <- data.frame(
  cell = rownames(Biobase::pData(cds)),
  pseudotime = Biobase::pData(cds)$Pseudotime,
  AUC = Biobase::pData(cds)$AUC,
  celltype = Biobase::pData(cds)$celltype
)


##Fig.7G(G-3)
p <- ggplot(df, aes(x = pseudotime, y = AUC)) +
  geom_point(aes(color = celltype), alpha = 0.9, size = 1)+ 
  geom_smooth(aes(group = 1), method = "loess", se = FALSE, color = "blue", size = 1) +
  scale_color_manual(values = cell_colors) +
  theme_minimal(base_size = 14) +
  theme(
    panel.border = element_rect(color = "black", fill = NA, size = 1), 
    panel.background = element_blank(),  
    plot.background = element_blank(),
    axis.ticks = element_line(color = "black", size = 0.5), 
    axis.ticks.length = unit(0.2, "cm")
  ) +labs(
    title = "83 Gene Score",
    x = "Pseudotime",
    y = "83 Gene Score",
    color = "celltype"
  )

##Fig.7F(F-3)
df <- data.frame(
  pseudotime = pData(cds)$Pseudotime,
  celltype = pData(cds)$celltype
)

p <- ggplot(df, aes(x = pseudotime, y = celltype, fill = celltype)) +
  geom_density_ridges(scale = 1.5, alpha = 0.9, color = "white") +
  scale_fill_manual(values = cell_colors) +
  labs(x = "Pseudotime", y = "celltype", title = "") +
  theme_bw(base_size = 14) + 
  theme(
    legend.position = "none",
    panel.border = element_rect(color = "black", fill = NA, size = 1),  
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    plot.title = element_text(hjust = 0.5)  
  )


##Fig.7H(H-3)
## Monocle trajectory colored by 83-gene AUC score
p <-  plot_cell_trajectory(cds, color_by = "AUC") +
  scale_color_viridis_c() +
  ggtitle("83gene score")


saveRDS(cds,"TAMacro_OD_monocle_cds.rds") 



##----------------------04MG: GBM-----------------------------------------##

MG<- subset( Myeloid,
             subset = celltype %in% c(
               "MG-Activation",
               "MG-Homeo",
               "MG-IFN",
               "MG-Inflam",
               "MG-Lipid"
             )
)

MG$celltype <- factor(
  MG$celltype,
  levels = c(
    "MG-Activation",
    "MG-Homeo",
    "MG-IFN",
    "MG-Inflam",
    "MG-Lipid"
  )
)

MG_GBM <- subset(MG, group == "GBM")

## A total of 38309 microglia cells were identified.
## To ensure computational feasibility in Monocle2, microglia cells were randomly
## downsampled before trajectory inference.
## A fixed random seed was used for reproducibility.
## Downsampling was applied only to Monocle2 pseudotime analysis and visualization.


subtype_col  <- "celltype"
target_total <- 18000      
stopifnot(subtype_col %in% colnames(MG_GBM@meta.data))
meta <- MG_GBM@meta.data %>% 
  mutate(.cell = colnames(MG_GBM),
         .subtype = .data[[subtype_col]])

apportion_largest_remainder <- function(n_vec, target){
  total <- sum(n_vec); raw <- n_vec/total*target
  base <- floor(raw); alloc <- pmin(base, n_vec)
  remain <- target - sum(alloc); frac <- raw - base
  if(remain > 0){
    ord <- order(frac, decreasing = TRUE)
    for(i in ord){ if(remain==0) break
      if(alloc[i] < n_vec[i]){ alloc[i] <- alloc[i] + 1; remain <- remain - 1 }
    }
  } else if(remain < 0){
    ord <- order(frac, decreasing = FALSE)
    for(i in ord){ if(remain==0) break
      if(alloc[i] > 0){ alloc[i] <- alloc[i] - 1; remain <- remain + 1 }
    }
  }
  stopifnot(sum(alloc) == target); alloc
}


size_tbl <- meta %>% count(.subtype, name = "n")
size_tbl$alloc <- apportion_largest_remainder(size_tbl$n, target_total)
message("Allocation by subtype:")
print(size_tbl)


alloc_df <- size_tbl %>% dplyr::select(.subtype, alloc)

sample_cells <- meta %>%
  inner_join(alloc_df, by = ".subtype") %>%
  group_by(.subtype) %>%
  group_modify(~ dplyr::slice_sample(.x, n = unique(.x$alloc))) %>%
  ungroup() %>%
  pull(.cell)

stopifnot(length(sample_cells) == target_total)
MG_GBM_sub <- subset(MG_GBM, cells = sample_cells)


data <- GetAssayData(MG_GBM_sub , assay = "RNA", slot = "counts")
pd <- new('AnnotatedDataFrame', data = MG_GBM_sub@meta.data)
fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
fd <- new('AnnotatedDataFrame', data = fData)

HSMM <- newCellDataSet(data,
                       phenoData = pd,
                       featureData = fd,
                       expressionFamily = negbinomial.size())
HSMM <- estimateSizeFactors(HSMM)
HSMM <- estimateDispersions(HSMM)
HSMM <- detectGenes(HSMM, min_expr = 0.1 )
print(head(fData(HSMM)))

expressed_genes <- row.names(subset(fData(HSMM),
                                    num_cells_expressed >= 10))
head(pData(HSMM))


mito_genes <- grep("^MT-", rownames(HSMM), value = TRUE)
ribo_genes <- grep("^RPS|^RPL", rownames(HSMM), value = TRUE)
candidate <- setdiff(expressed_genes, c(mito_genes, ribo_genes))


diff_test_res <- differentialGeneTest(HSMM[candidate,],      
                                      fullModelFormulaStr = "~ celltype",
                                      cores = 30)

ordering_genes <- subset(diff_test_res, qval < 0.01)
ordering_genes <- ordering_genes[order(ordering_genes$qval),]
ordering_genes <- rownames(ordering_genes)[1:1000]

HSMM <- setOrderingFilter(HSMM, ordering_genes)
plot_ordering_genes(HSMM)

HSMM <- reduceDimension(HSMM, max_components = 2,
                        method = 'DDRTree'
)
HSMM <- orderCells(HSMM)

table(pData(HSMM)$State,pData(HSMM)$celltype)     

cds <- orderCells(HSMM, root_state = 1) 


MG_GBM_sub$Pseudotime <- Biobase::pData(cds)[colnames(MG_GBM_sub), "Pseudotime"]

p <- plot_cell_trajectory(cds,color_by="Pseudotime") 

signature <- read.xlsx("signature.xlsx",1)
IDHWT     <-  na.omit(signature$IDHWT)

##AUC Score
exprMatrix <-  GetAssayData(MG_GBM_sub, assay = "RNA", slot = "counts")
cells_AUC2 <-  AUCell_run(exprMatrix, IDHWT)
AUCell_auc <-  cells_AUC2@assays@data@listData[["AUC"]]
MG_GBM_sub$AUC <- AUCell_auc
common_cells <- intersect(
  rownames(pData(cds)),
  colnames(MG_GBM_sub)
)
Biobase::pData(cds)[common_cells, "AUC"] <- MG_GBM_sub$AUC[common_cells]


##179-gene signature score along pseudotime
df <- data.frame(
  cell = rownames(Biobase::pData(cds)),
  pseudotime = Biobase::pData(cds)$Pseudotime,
  AUC = Biobase::pData(cds)$AUC, 
  celltype = Biobase::pData(cds)$celltype
)


##Fig.7J(J-1)
p <- ggplot(df, aes(x = pseudotime, y = AUC)) +
  geom_point(aes(color = celltype), alpha = 0.9, size = 1)+ 
  geom_smooth(aes(group = 1), method = "loess", se = FALSE, color = "blue", size = 1) +
  scale_color_manual(values = cell_colors) +
  theme_minimal(base_size = 14) +
  theme(
    panel.border = element_rect(color = "black", fill = NA, size = 1), 
    panel.background = element_blank(),  
    plot.background = element_blank(),
    axis.ticks = element_line(color = "black", size = 0.5), 
    axis.ticks.length = unit(0.2, "cm")
  ) +labs(
    title = "179 Gene Score",
    x = "Pseudotime",
    y = "179 Gene Score",
    color = "celltype"
  )

##Fig.7I(I-1)
df <- data.frame(
  pseudotime = pData(cds)$Pseudotime,
  celltype = pData(cds)$celltype
)

p <- ggplot(df, aes(x = pseudotime, y = celltype, fill = celltype)) +
  geom_density_ridges(scale = 1.5, alpha = 0.9, color = "white") +
  scale_fill_manual(values = cell_colors) +
  labs(x = "Pseudotime", y = "celltype", title = "") +
  theme_bw(base_size = 14) +  
  theme(
    legend.position = "none",
    panel.border = element_rect(color = "black", fill = NA, size = 1),  
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),  
    plot.title = element_text(hjust = 0.5)  
  )


##Fig.7K(K-1)
## Monocle trajectory colored by 179-gene AUC score
p <-  plot_cell_trajectory(cds, color_by = "AUC") +
  scale_color_viridis_c() +
  ggtitle("179gene score")

saveRDS(cds,"MG_GBM_monocle_cds.rds") 




##------------------------05 MG: Astrocytoma--------------------------##
MG_Astro <- subset(MG, group == "Astrocytoma")
data <- GetAssayData(MG_Astro , assay = "RNA", slot = "counts")
data <- as(as.matrix(data),'sparseMatrix')


pd <- new('AnnotatedDataFrame', data = MG_Astro@meta.data)
fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
fd <- new('AnnotatedDataFrame', data = fData)


HSMM <- newCellDataSet(data,
                       phenoData = pd,
                       featureData = fd,
                       expressionFamily = negbinomial.size())
HSMM <- estimateSizeFactors(HSMM)
HSMM <- estimateDispersions(HSMM,cores=30)
HSMM <- detectGenes(HSMM, min_expr = 0.1 )
print(head(fData(HSMM)))

expressed_genes <- row.names(subset(fData(HSMM),
                                    num_cells_expressed >= 10))
head(pData(HSMM))


mito_genes <- grep("^MT-", rownames(HSMM), value = TRUE)
ribo_genes <- grep("^RPS|^RPL", rownames(HSMM), value = TRUE)
candidate <- setdiff(expressed_genes, c(mito_genes, ribo_genes))


diff_test_res <- differentialGeneTest(HSMM[candidate,],       
                                      fullModelFormulaStr = "~ celltype",
                                      cores = 30)

ordering_genes <- subset(diff_test_res, qval < 0.01)
ordering_genes <- ordering_genes[order(ordering_genes$qval),]
ordering_genes <- rownames(ordering_genes)[1:1000]

HSMM <- setOrderingFilter(HSMM, ordering_genes)
plot_ordering_genes(HSMM)
HSMM <- reduceDimension(HSMM, max_components = 2,
                        method = 'DDRTree')
HSMM <- orderCells(HSMM)

table(pData(HSMM)$State,pData(HSMM)$celltype)     


cds <- orderCells(HSMM,root_state = 5)

MG_Astro$Pseudotime <- 
  Biobase::pData(cds)[colnames(MG_Astro), "Pseudotime"]

p <- plot_cell_trajectory(cds,color_by="Pseudotime") 

signature <- read.xlsx("signature.xlsx",1)
Noncodel    <-  na.omit(signature$Noncodel)

##AUC Score
exprMatrix <-  GetAssayData(MG_Astro, assay = "RNA", slot = "counts")
cells_AUC2 <-  AUCell_run(exprMatrix, Noncodel)
AUCell_auc <-  cells_AUC2@assays@data@listData[["AUC"]]
MG_Astro$AUC <- AUCell_auc
common_cells <- intersect(
  rownames(pData(cds)),
  colnames(MG_Astro)
)
Biobase::pData(cds)[common_cells, "AUC"] <- MG_Astro$AUC[common_cells]


##30-gene signature score along pseudotime
df <- data.frame(
  cell = rownames(Biobase::pData(cds)),
  pseudotime = Biobase::pData(cds)$Pseudotime,
  AUC = Biobase::pData(cds)$AUC,
  celltype = Biobase::pData(cds)$celltype
)


##Fig.7J(J-2)
p <- ggplot(df, aes(x = pseudotime, y = AUC)) +
  geom_point(aes(color = celltype), alpha = 0.9, size = 1)+ 
  geom_smooth(aes(group = 1), method = "loess", se = FALSE, color = "blue", size = 1) +
  scale_color_manual(values = cell_colors) +
  theme_minimal(base_size = 14) +
  theme(
    panel.border = element_rect(color = "black", fill = NA, size = 1), 
    panel.background = element_blank(),  
    plot.background = element_blank(),
    axis.ticks = element_line(color = "black", size = 0.5), 
    axis.ticks.length = unit(0.2, "cm")
  ) +labs(
    title = "30 Gene Score",
    x = "Pseudotime",
    y = "30 Gene Score",
    color = "celltype"
  )

##Fig.7I(I-2)
df <- data.frame(
  pseudotime = pData(cds)$Pseudotime,
  celltype = pData(cds)$celltype
)

p <- ggplot(df, aes(x = pseudotime, y = celltype, fill = celltype)) +
  geom_density_ridges(scale = 1.5, alpha = 0.9, color = "white") +
  scale_fill_manual(values = cell_colors) +
  labs(x = "Pseudotime", y = "celltype", title = "") +
  theme_bw(base_size = 14) + 
  theme(
    legend.position = "none",
    panel.border = element_rect(color = "black", fill = NA, size = 1),  
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),  
    plot.title = element_text(hjust = 0.5) 
  )


##Fig.7K(k-2)
## Monocle trajectory colored by 30-gene AUC score
p <-  plot_cell_trajectory(cds, color_by = "AUC") +
  scale_color_viridis_c() +
  ggtitle("30gene score")


saveRDS(cds,"MG_AC_monocle_cds.rds") 


##-------------------MG: Oligodendroglioma --------------------------##
MG_OD <- subset(MG, group == "Oligodendroglioma")
data <- GetAssayData(MG_OD , assay = "RNA", slot = "counts")
data <- as(as.matrix(data),'sparseMatrix')

pd <- new('AnnotatedDataFrame', data = MG_OD@meta.data)
fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
fd <- new('AnnotatedDataFrame', data = fData)

HSMM <- newCellDataSet(data,
                       phenoData = pd,
                       featureData = fd,
                       expressionFamily = negbinomial.size())
HSMM <- estimateSizeFactors(HSMM)
HSMM <- estimateDispersions(HSMM,cores=30)
HSMM <- detectGenes(HSMM, min_expr = 0.1 )
print(head(fData(HSMM)))

expressed_genes <- row.names(subset(fData(HSMM),
                                    num_cells_expressed >= 10))
head(pData(HSMM))


mito_genes <- grep("^MT-", rownames(HSMM), value = TRUE)
ribo_genes <- grep("^RPS|^RPL", rownames(HSMM), value = TRUE)
candidate <- setdiff(expressed_genes, c(mito_genes, ribo_genes))


diff_test_res <- differentialGeneTest(HSMM[candidate,],      
                                      fullModelFormulaStr = "~ celltype",
                                      cores = 30)

ordering_genes <- subset(diff_test_res, qval < 0.01)
ordering_genes <- ordering_genes[order(ordering_genes$qval),]
ordering_genes <- rownames(ordering_genes)[1:1000]


HSMM <- setOrderingFilter(HSMM, ordering_genes)
plot_ordering_genes(HSMM)
HSMM <- reduceDimension(HSMM, max_components = 2,
                        method = 'DDRTree')
HSMM <- orderCells(HSMM)

table(pData(HSMM)$State,pData(HSMM)$celltype)     

cds <- orderCells(HSMM, root_state = 7) 

MG_OD$Pseudotime <- 
  Biobase::pData(cds)[colnames(MG_OD), "Pseudotime"]

p <- plot_cell_trajectory(cds,color_by="Pseudotime") 

signature <- read.xlsx("signature.xlsx",1)
Codel     <-  na.omit(signature$Codel)

##AUC Score
exprMatrix <-  GetAssayData(MG_OD, assay = "RNA", slot = "counts")
cells_AUC2 <-  AUCell_run(exprMatrix, Codel)
AUCell_auc <-  cells_AUC2@assays@data@listData[["AUC"]]
MG_OD$AUC <- AUCell_auc
common_cells <- intersect(
  rownames(pData(cds)),
  colnames(MG_OD)
)
Biobase::pData(cds)[common_cells, "AUC"] <- MG_OD$AUC[common_cells]


##83-gene signature score along pseudotime
df <- data.frame(
  cell = rownames(Biobase::pData(cds)),
  pseudotime = Biobase::pData(cds)$Pseudotime,
  AUC = Biobase::pData(cds)$AUC,
  celltype = Biobase::pData(cds)$celltype
)


##Fig.7J(J-3)
p <- ggplot(df, aes(x = pseudotime, y = AUC)) +
  geom_point(aes(color = celltype), alpha = 0.9, size = 1)+ 
  geom_smooth(aes(group = 1), method = "loess", se = FALSE, color = "blue", size = 1) +
  scale_color_manual(values = cell_colors) +
  theme_minimal(base_size = 14) +
  theme(
    panel.border = element_rect(color = "black", fill = NA, size = 1), 
    panel.background = element_blank(),  
    plot.background = element_blank(),
    axis.ticks = element_line(color = "black", size = 0.5), 
    axis.ticks.length = unit(0.2, "cm")
  ) +labs(
    title = "83 Gene Score",
    x = "Pseudotime",
    y = "83 Gene Score",
    color = "celltype"
  )

##Fig.7I(I-3)
df <- data.frame(
  pseudotime = pData(cds)$Pseudotime,
  celltype = pData(cds)$celltype
)

p <- ggplot(df, aes(x = pseudotime, y = celltype, fill = celltype)) +
  geom_density_ridges(scale = 1.5, alpha = 0.9, color = "white") +
  scale_fill_manual(values = cell_colors) +
  labs(x = "Pseudotime", y = "celltype", title = "") +
  theme_bw(base_size = 14) + 
  theme(
    legend.position = "none",
    panel.border = element_rect(color = "black", fill = NA, size = 1),  
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    plot.title = element_text(hjust = 0.5)  
  )


##Fig.7K(K-3)
## Monocle trajectory colored by 83-gene AUC score
p <-  plot_cell_trajectory(cds, color_by = "AUC") +
  scale_color_viridis_c() +
  ggtitle("83gene score")


saveRDS(cds,"MG_OD_monocle_cds.rds") 







