## ================================================================
## T cell downstream analysis
## ================================================================
##
## This script performs downstream analyses of T/NK/B lineage cells
## in glioma, including T cell subcluster visualization, cell proportion
## analysis, Ro/e enrichment analysis, BayesPrism-based bulk RNA-seq
## deconvolution, survival analysis, AUCell-based subtype-related
## gene-set scoring, and Monocle2 pseudotime analysis for CD4 T and
## CD8 T cells.
##
## -------------------------
## Required input files
## -------------------------
##
## 1. T_cell.rds
##    A processed Seurat object containing annotated T/NK/B lineage cells.
##    Required metadata columns include:
##      - celltype
##      - group
##      - tumor_type
##    The RNA assay should contain raw count data.
##
## 2. signature.xlsx
##    An Excel file containing subtype-related gene signatures.
##    Required columns include:
##      - IDHWT
##      - IDHMU
##      - Noncodel
##      - Codel
##
## 3. 整理过的TCGAGBMLGG全数据_需要log2.xlsx
##    A processed TCGA GBM/LGG bulk RNA-seq expression matrix with
##    survival information. The file should contain overall survival
##    time, survival status, and gene expression values for each sample.
##
## -------------------------
## Main output files
## -------------------------
##
## 1. BayesPrism-inferred T cell fraction.csv
##    BayesPrism-inferred T/NK/B cell subcluster fractions for TCGA
##    GBM/LGG bulk RNA-seq samples, combined with survival metadata.
##
## 2. survival/
##    A folder containing Kaplan-Meier survival plots for each
##    BayesPrism-inferred T/NK/B cell subcluster fraction.
##
## 3. CD4T_GBM_monocle_cds.rds
##    Monocle2 CellDataSet object for CD4 T cells in GBM.
##
## 4. CD4T_Astro_monocle_cds.rds
##    Monocle2 CellDataSet object for CD4 T cells in astrocytoma.
##
## 5. CD4T_OD_monocle_cds.rds
##    Monocle2 CellDataSet object for CD4 T cells in oligodendroglioma.
##
## 6. CD8T_GBM_monocle_cds.rds
##    Monocle2 CellDataSet object for CD8 T cells in GBM.
##
## 7. CD8T_Astro_monocle_cds.rds
##    Monocle2 CellDataSet object for CD8 T cells in astrocytoma.
##
## 8. CD8T_OD_monocle_cds.rds
##    Monocle2 CellDataSet object for CD8 T cells in oligodendroglioma.
##
## -------------------------
## Main analyses generated by this script
## -------------------------
##
## 1. T/NK/B cell subcluster visualization.
## 2. T/NK/B cell subcluster proportion analysis across glioma molecular groups.
## 3. Ro/e enrichment analysis of T/NK/B cell subclusters across glioma molecular groups.
## 4. BayesPrism-based deconvolution of T/NK/B cell subcluster fractions in bulk RNA-seq data.
## 5. Survival analysis based on inferred T/NK/B cell subcluster fractions.
## 6. AUCell scoring of subtype-related gene signatures in T/NK/B cells.
## 7. Monocle2 pseudotime analysis of CD4 T cells.
## 8. Monocle2 pseudotime analysis of CD8 T cells.
## 9. Pseudotime-associated subtype-related gene-set score visualization.
## ================================================================



if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
if (!requireNamespace("Seurat", quietly = TRUE)) {
  remotes::install_github("satijalab/seurat", ref = "seurat5", quiet = TRUE)
}
if (!requireNamespace("devtools", quietly = TRUE)) {
  install.packages("devtools")
}
if (!requireNamespace("Startrac", quietly = TRUE)) {
  remotes::install_github("Japrin/STARTRAC", quiet = TRUE)
}
if (!requireNamespace("RColorBrewer", quietly = TRUE)) {
  install.packages("RColorBrewer")
}
if (!requireNamespace("pheatmap", quietly = TRUE)) {
  install.packages("pheatmap")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("dplyr", quietly = TRUE)) {
  install.packages("dplyr")
}
if (!requireNamespace("openxlsx", quietly = TRUE)) {
  install.packages("openxlsx")
}
if (!requireNamespace("tibble", quietly = TRUE)) {
  install.packages("tibble")
}

library(Seurat)
library(Startrac)
library(RColorBrewer)
library(pheatmap)
library(ggplot2)
library(dplyr)
library(openxlsx)
library(tibble)

T_cell <- readRDS("T_cell.rds")

cell_colors <- c(
  "CD4-Tcm"        =   "#67a8cd",
  "CD4-Tn"         =   "#a6542c",
  "CD4-Treg"       =   "#c77eb5",
  "CD8-Tem"        =   "#A6CEE3",
  "CD8-Teff"       =   "#A6C990",
  "CD8-Prolif"     =   "#45b97c",
  "NK-XCL1"        =   "#FDBF6F",
  "NK-FCGR3A"      =   "#e63836",
  "CD8-Pre-Tex"    =   "#f7acbc",
  "CD8-IFN"        =   "#8552a1",
  "B cells"        =   "#1F78B4"
)
T_cell$tumor_type <- factor(
  T_cell$tumor_type,
  levels = c("WT", "M-N", "M-C")
)

##--Fig8A---------------------------------------------##

p <- DimPlot(T_cell, reduction = "tsne",label=T,cols = cell_colors)

##--Fig8B----- cell proportion----------------------------##
meta.data <- T_cell@meta.data

meta.data$celltype <- factor(
  meta.data$celltype,
  levels = c(
    "CD4-Tn",
    "CD4-Tcm",
    "CD4-Treg",
    "CD8-Tem",
    "CD8-Teff",
    "CD8-IFN",
    "CD8-Pre-Tex",
    "CD8-Prolif",
    "NK-FCGR3A",
    "NK-XCL1",
    "B cells"
  )
)

meta.data$tumor_type <- factor(
  meta.data$tumor_type,
  levels = c("WT", "M-N", "M-C")
)

sub_data <- table(meta.data$tumor_type, meta.data$celltype) %>% 
  as.data.frame() %>% 
  group_by(Var1) %>% 
  mutate(
    cell_proportion = Freq/sum(Freq)
  )
colnames(sub_data) <- c("sample", "cluster", "cell_num", "cell_proportion")

p <- ggplot(sub_data)+
  geom_col(aes(x = sample, y = cell_proportion, fill = cluster), position = 'stack', width = 0.6)+
  theme_bw()+
  theme(
    panel.background = element_blank(),
    axis.text.x = element_text(
      angle = 90
    )
  )+scale_fill_manual(values = cell_colors)


##-Fig8C-------------Roe Score-----------------------------##
Roe <- calTissueDist(meta.data,
                     colname.cluster = "celltype", 
                     colname.tissue = "tumor_type", 
                     method = "chisq", 
                     min.rowSum = 0) 
colours  <- colorRampPalette(brewer.pal(9, "OrRd"))(50)

ph  <- pheatmap(Roe,
                border_color = "black",
                border=F,
                color = colours,
                scale = 'none',
                fontsize_row = 12,
                fontsize_col = 6,
                drop_levels=F,
                show_rownames = T,
                show_colnames = T,
                cluster_cols = F,
                cluster_rows = F,
                display_numbers = TRUE,
                cellwidth = 20, 
                cellheight = 20,
                
)


##--------------------------------------------------------------------------##

##Fig8D------Bulk RNA-seq deconvolution using BayesPrism---------------------##

##---------------------------------------------------------------------------##
if (!requireNamespace("survminer", quietly = TRUE)) {
  install.packages("survminer")
}
if (!requireNamespace("survival", quietly = TRUE)) {
  install.packages("survival")
}
if (!requireNamespace("BayesPrism", quietly = TRUE)) {
  remotes::install_github("Danko-Lab/BayesPrism/BayesPrism")
}

library(BayesPrism)
library(survival)
library(survminer)
species = "hs"  

sc.dat <-  as.matrix(t(GetAssayData(T_cell, assay = "RNA", slot = "counts")))
cell.type.labels<-T_cell@meta.data$celltype  
cell.state.labels<-NULL   

#1,QC of cell type and state labels
plot.cor.phi (input=sc.dat, 
              input.labels=cell.type.labels, 
              title="cell type correlation",
              cexRow=0.5, cexCol=0.5,
)

#2,Filter outlier genes
sc.stat <- plot.scRNA.outlier(
  input=sc.dat, 
  cell.type.labels=cell.type.labels,
  species=species, 
  return.raw=TRUE
)

sc.dat.filtered <- cleanup.genes (input=sc.dat,
                                  input.type="count.matrix",
                                  species=species, 
                                  gene.group=c( "Rb","Mrp","other_Rb","chrM","MALAT1","chrX","chrY") ,
                                  exp.cells=5)

sc.dat.filtered.pc <-  select.gene.type (sc.dat.filtered,
                                         gene.type = "protein_coding")

library(openxlsx)
exp <- read.xlsx("整理过的TCGAGBMLGG全数据_需要log2.xlsx")
rownames(exp) <- exp[,1]
exp <- exp[,-1]
exp <- as.data.frame(t(exp))

metadata <- exp[,c(4:5)]
names(metadata) <- c("OS.time","OS")
metadata$OS     <- as.numeric (metadata$OS)
metadata$OS.time <- as.numeric (metadata$OS.time)


n <- ncol(exp)
exp<- exp[,c(13:n)]
exp <- as.data.frame(t(exp))
Symbol <- rownames(exp)
Sample  <- names(exp)
exp <- as.data.frame(lapply(exp,as.numeric))
rownames(exp) <- Symbol


bk.dat<-as.matrix(t(exp))

bk.stat <- plot.bulk.outlier(
  bulk.input=bk.dat,
  sc.input=sc.dat,
  cell.type.labels=cell.type.labels,
  species=species, 
  return.raw=TRUE
)

plot.bulk.vs.sc (sc.input = sc.dat.filtered,
                 bulk.input = bk.dat
             
)

myPrism <- new.prism(
  reference=sc.dat.filtered.pc, 
  mixture=bk.dat,
  input.type="count.matrix", 
  cell.type.labels = cell.type.labels, 
  cell.state.labels = NULL,
  key=NULL,
  outlier.cut=0.01,
  outlier.fraction=0.1)

bp.res <- run.prism(prism = myPrism, n.cores=30)


score <- get.fraction(bp=bp.res,
                      which.theta="final",
                      state.or.type="type")
score <- as.data.frame(score)
score <- rownames_to_column(score, "id")

metadata <- rownames_to_column(metadata, "id")
metadata_score <-left_join(metadata,score,by="id")
write.csv(metadata_score,"BayesPrism-inferred T cell fraction.csv",row.names = F)


dir.create("survival", showWarnings = FALSE)
for (i in colnames(metadata_score)[4:ncol(metadata_score)]) {
  
  rt <- metadata_score
  med <- median(rt[[i]], na.rm = TRUE)
  rt$group <- ifelse(rt[[i]] > med, "High", "Low")
  rt$group <- factor(rt$group, levels = c("High", "Low"))
  diff <- survdiff(Surv(OS.time, OS) ~ group, data = rt)
  p <- 1 - pchisq(diff$chisq, df = 1)
  
  if (p < 0.0001) {
    pValue <- "p < 0.0001"
  } else {
    pValue <- paste0("p = ", sprintf("%.4f", p))
  }
  
  fit <- survfit(Surv(OS.time, OS) ~ group, data = rt)
  surPlot <- ggsurvplot(
    fit,
    data = rt,
    pval = pValue,
    risk.table = FALSE,
    ggtheme = theme_classic() +
      theme(
        axis.text = element_text(color = "black", size = 7),
        axis.title = element_text(color = "black"),
        panel.grid = element_blank()
      ),
    censor.shape = 124,
    censor.size = 2,
    conf.int = FALSE,
    legend.labs = c("High", "Low"),
    legend.title = i,
    xlab = "Overall survival (months)",
    ylab = "Survival probability",
    palette = c("#E31A1C", "#1F78B4")
  )
  pdf(
    paste0("survival/", i, ".pdf"),
    onefile = FALSE,
    width = 5.5,
    height = 5
  )
  print(surPlot)
  dev.off()
}


##--------------------------------------------------------------------------##

##Fig8E---------------------179,68,30,83 gene score----------------------##

##---------------------------------------------------------------------------##


if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")
}
if (!requireNamespace("AUCell", quietly = TRUE)) {
  BiocManager::install("AUCell")
}
if (!requireNamespace("Matrix", quietly = TRUE)) {
  install.packages("Matrix")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("scales", quietly = TRUE)) {
  install.packages("scales")
}

library(AUCell)
library(Matrix)
library(ggplot2)
library(scales)

signature  <- read.xlsx("signature.xlsx",1)

gene_179<- na.omit(signature$IDHWT)
gene_68 <- na.omit(signature$IDHMU)
gene_30 <- na.omit(signature$Noncodel)
gene_83 <- na.omit(signature$Codel)


expr <- GetAssayData(T_cell, assay = "RNA", slot = "counts")
gene_sets <- list(
  gene_179 = gene_179,   
  gene_68  = gene_68,
  gene_30  = gene_30,
  gene_83  = gene_83
)

cells_AUC <- AUCell_run(expr, gene_sets)
auc_mat <- t(getAUC(cells_AUC))[colnames(T_cell), ]
T_cell@meta.data <- cbind(T_cell@meta.data, auc_mat)

##The drawing code is already available in Gene set score

##--------------------------------------------------------------------------##

##Fig8F,G,H,I,J,K------ GBM,Astrocytoma,Oligodendroglioma--monocle-----------------##

##---------------------------------------------------------------------------##

##-------------------01CD4T GBM-------------------------##
if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")
}
if (!requireNamespace("monocle", quietly = TRUE)) {
  BiocManager::install("monocle", ask = FALSE, update = FALSE)
}
if (!requireNamespace("AUCell", quietly = TRUE)) {
  BiocManager::install("AUCell", ask = FALSE, update = FALSE)
}
if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
if (!requireNamespace("Seurat", quietly = TRUE)) {
  remotes::install_github("satijalab/seurat", ref = "seurat5", quiet = TRUE)
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("openxlsx", quietly = TRUE)) {
  install.packages("openxlsx")
}
if (!requireNamespace("dplyr", quietly = TRUE)) {
  install.packages("dplyr")
}
if (!requireNamespace("ggridges", quietly = TRUE)) {
  install.packages("ggridges")
}


library(monocle)
library(Seurat)
library(ggplot2)
library(AUCell)     
library(openxlsx)
library(dplyr)
library(ggridges)

CD4_T   <- subset(T_cell, subset = celltype %in% c("CD4-Tn","CD4-Tcm","CD4-Treg" ))

CD4_T $celltype <- factor(
  CD4_T$celltype,
  levels = c(
    "CD4-Tn",
    "CD4-Tcm",
    "CD4-Treg"   
  )
)
table(CD4_T$celltype)

CD4_T_GBM    <-  subset(CD4_T, subset = group == "GBM")

data <- GetAssayData(CD4_T_GBM, assay = "RNA", slot = "counts")
data <- as(as.matrix(data),'sparseMatrix')


pd <- new('AnnotatedDataFrame', data = CD4_T_GBM@meta.data)
fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
fd <- new('AnnotatedDataFrame', data = fData)


HSMM <- newCellDataSet(data,
                       phenoData = pd,
                       featureData = fd,
                       expressionFamily = negbinomial.size())
HSMM <- estimateSizeFactors(HSMM)
HSMM <- estimateDispersions(HSMM,cores=30)
HSMM <- detectGenes(HSMM, min_expr = 0.1 )
print(head(fData(HSMM)))

expressed_genes <- row.names(subset(fData(HSMM),
                                    num_cells_expressed >= 10))
head(pData(HSMM))

mito_genes <- grep("^MT-", rownames(HSMM), value = TRUE)
ribo_genes <- grep("^RPS|^RPL", rownames(HSMM), value = TRUE)
candidate <- setdiff(expressed_genes, c(mito_genes, ribo_genes))

diff_test_res <- differentialGeneTest(HSMM[candidate,],  
                                      fullModelFormulaStr = "~ celltype",
                                      cores = 30)
ordering_genes <- row.names(subset(diff_test_res, qval < 0.01)) 

HSMM <- setOrderingFilter(HSMM, ordering_genes)
plot_ordering_genes(HSMM)
HSMM <- reduceDimension(HSMM, max_components = 2,
                        method = 'DDRTree')
HSMM <- orderCells(HSMM)

table(pData(HSMM)$State,pData(HSMM)$celltype)     

cds <- orderCells(HSMM, root_state = 1) 


CD4_T_GBM$Pseudotime <- Biobase::pData(cds)[colnames(CD4_T_GBM), "Pseudotime"]

p <- plot_cell_trajectory(cds,color_by="Pseudotime") 

signature <- read.xlsx("signature.xlsx",1)
IDHWT     <-  na.omit(signature$IDHWT)

##AUC Score
exprMatrix <-  GetAssayData(CD4_T_GBM, assay = "RNA", slot = "counts")
cells_AUC2 <-  AUCell_run(exprMatrix, IDHWT)
AUCell_auc <-  cells_AUC2@assays@data@listData[["AUC"]]
CD4_T_GBM$AUC <- AUCell_auc
common_cells <- intersect(
  rownames(pData(cds)),
  colnames(CD4_T_GBM)
)
Biobase::pData(cds)[common_cells, "AUC"] <- CD4_T_GBM$AUC[common_cells]


##179-gene signature score along pseudotime
df <- data.frame(
  cell = rownames(Biobase::pData(cds)),
  pseudotime = Biobase::pData(cds)$Pseudotime,
  AUC = Biobase::pData(cds)$AUC,
  celltype = Biobase::pData(cds)$celltype
)


##Fig.8G(G-1)
p <- ggplot(df, aes(x = pseudotime, y = AUC)) +
  geom_point(aes(color = celltype), alpha = 0.9, size = 1)+ 
  geom_smooth(aes(group = 1), method = "loess", se = FALSE, color = "blue", size = 1) +
  scale_color_manual(values = cell_colors) +
  theme_minimal(base_size = 14) +
  theme(
    panel.border = element_rect(color = "black", fill = NA, size = 1), 
    panel.background = element_blank(),  
    plot.background = element_blank(),
    axis.ticks = element_line(color = "black", size = 0.5), 
    axis.ticks.length = unit(0.2, "cm"),
  ) +labs(
    title = "179 Gene Score",
    x = "Pseudotime",
    y = "179 Gene Score",
    color = "celltype"
  )

##Fig.8F(F-1)
df <- data.frame(
  pseudotime = pData(cds)$Pseudotime,
  celltype = pData(cds)$celltype
)

p <- ggplot(df, aes(x = pseudotime, y = celltype, fill = celltype)) +
  geom_density_ridges(scale = 1.5, alpha = 0.9, color = "white") +
  scale_fill_manual(values = cell_colors) +
  labs(x = "Pseudotime", y = "celltype", title = "") +
  theme_bw(base_size = 14) +  
  theme(
    legend.position = "none",
    panel.border = element_rect(color = "black", fill = NA, size = 1), 
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),  
    plot.title = element_text(hjust = 0.5)  
  )


##Fig.8H(H-1)
## Monocle trajectory colored by 179-gene AUC score
p <-  plot_cell_trajectory(cds, color_by = "AUC") +
  scale_color_viridis_c() +
  ggtitle("179gene score")

saveRDS(cds,"CD4T_GBM_monocle_cds.rds") 



##-------------------02CD4T Astrocytoma-------------------------##
CD4_T_Astro    <-  subset(CD4_T, subset = group == c("Astrocytoma"))

data <- GetAssayData(CD4_T_Astro, assay = "RNA", slot = "counts")
data <- as(as.matrix(data),'sparseMatrix')


pd <- new('AnnotatedDataFrame', data = CD4_T_Astro@meta.data)
fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
fd <- new('AnnotatedDataFrame', data = fData)

HSMM <- newCellDataSet(data,
                       phenoData = pd,
                       featureData = fd,
                       expressionFamily = negbinomial.size())
HSMM <- estimateSizeFactors(HSMM)
HSMM <- estimateDispersions(HSMM,cores=30)
HSMM <- detectGenes(HSMM, min_expr = 0.1 )
print(head(fData(HSMM)))

expressed_genes <- row.names(subset(fData(HSMM),
                                    num_cells_expressed >= 10))
head(pData(HSMM))


mito_genes <- grep("^MT-", rownames(HSMM), value = TRUE)
ribo_genes <- grep("^RPS|^RPL", rownames(HSMM), value = TRUE)
candidate <- setdiff(expressed_genes, c(mito_genes, ribo_genes))


diff_test_res <- differentialGeneTest(HSMM[candidate,],      
                                      fullModelFormulaStr = "~ celltype",
                                      cores = 30)

ordering_genes <- row.names (subset(diff_test_res, qval < 0.01)) 


HSMM <- setOrderingFilter(HSMM, ordering_genes)
plot_ordering_genes(HSMM)
HSMM <- reduceDimension(HSMM, max_components = 2,
                        method = 'DDRTree')
HSMM <- orderCells(HSMM)

table(pData(HSMM)$State,pData(HSMM)$celltype)     

cds <- orderCells(HSMM, root_state = 3) 


CD4_T_Astro$Pseudotime <- 
  Biobase::pData(cds)[colnames(CD4_T_Astro), "Pseudotime"]

p <- plot_cell_trajectory(cds,color_by="Pseudotime") 


signature <- read.xlsx("signature.xlsx",1)
Noncodel    <-  na.omit(signature$Noncodel)

##AUC Score
exprMatrix <-  GetAssayData(CD4_T_Astro, assay = "RNA", slot = "counts")
cells_AUC2 <-  AUCell_run(exprMatrix, Noncodel)
AUCell_auc <-  cells_AUC2@assays@data@listData[["AUC"]]
CD4_T_Astro$AUC <- AUCell_auc
common_cells <- intersect(
  rownames(pData(cds)),
  colnames(CD4_T_Astro)
)
Biobase::pData(cds)[common_cells, "AUC"] <- CD4_T_Astro$AUC[common_cells]


##30-gene signature score along pseudotime
df <- data.frame(
  cell = rownames(Biobase::pData(cds)),
  pseudotime = Biobase::pData(cds)$Pseudotime,
  AUC = Biobase::pData(cds)$AUC,
  celltype = Biobase::pData(cds)$celltype
)


##Fig.8G(G-2)
p <- ggplot(df, aes(x = pseudotime, y = AUC)) +
  geom_point(aes(color = celltype), alpha = 0.9, size = 1)+ 
  geom_smooth(aes(group = 1), method = "loess", se = FALSE, color = "blue", size = 1) +
  scale_color_manual(values = cell_colors) +
  theme_minimal(base_size = 14) +
  theme(
    panel.border = element_rect(color = "black", fill = NA, size = 1), 
    panel.background = element_blank(),  
    plot.background = element_blank(),
    axis.ticks = element_line(color = "black", size = 0.5), 
    axis.ticks.length = unit(0.2, "cm"),
  ) +labs(
    title = "30 Gene Score",
    x = "Pseudotime",
    y = "30 Gene Score",
    color = "celltype"
  )

##Fig.8F(F-2)
df <- data.frame(
  pseudotime = pData(cds)$Pseudotime,
  celltype = pData(cds)$celltype
)

p <- ggplot(df, aes(x = pseudotime, y = celltype, fill = celltype)) +
  geom_density_ridges(scale = 1.5, alpha = 0.9, color = "white") +
  scale_fill_manual(values = cell_colors) +
  labs(x = "Pseudotime", y = "celltype", title = "") +
  theme_bw(base_size = 14) +  
  theme(
    legend.position = "none",
    panel.border = element_rect(color = "black", fill = NA, size = 1),  
    panel.grid.major = element_blank(),  
    panel.grid.minor = element_blank(),  
    plot.title = element_text(hjust = 0.5)  
  )


##Fig.8H(H-2)
## Monocle trajectory colored by 30-gene AUC score
p <-  plot_cell_trajectory(cds, color_by = "AUC") +
  scale_color_viridis_c() +
  ggtitle("30gene score")


saveRDS(cds,"CD4T_Astro_monocle_cds.rds") 


##-------------------03 CD4T Oligodendroglioma ---------------------##
CD4_T_OD    <-  subset(CD4_T, subset = group == c("Oligodendroglioma"))

data <- GetAssayData(CD4_T_OD, assay = "RNA", slot = "counts")
data <- as(as.matrix(data),'sparseMatrix')


pd <- new('AnnotatedDataFrame', data = CD4_T_OD@meta.data)
fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
fd <- new('AnnotatedDataFrame', data = fData)


HSMM <- newCellDataSet(data,
                       phenoData = pd,
                       featureData = fd,
                       expressionFamily = negbinomial.size())
HSMM <- estimateSizeFactors(HSMM)
HSMM <- estimateDispersions(HSMM,cores=30)
HSMM <- detectGenes(HSMM, min_expr = 0.1 )
print(head(fData(HSMM)))

expressed_genes <- row.names(subset(fData(HSMM),
                                    num_cells_expressed >= 10))
head(pData(HSMM))


mito_genes <- grep("^MT-", rownames(HSMM), value = TRUE)
ribo_genes <- grep("^RPS|^RPL", rownames(HSMM), value = TRUE)
candidate <- setdiff(expressed_genes, c(mito_genes, ribo_genes))



diff_test_res <- differentialGeneTest(HSMM[candidate,],      
                                      fullModelFormulaStr = "~ celltype",
                                      cores = 30)

ordering_genes <- row.names (subset(diff_test_res, qval < 0.01)) 


HSMM <- setOrderingFilter(HSMM, ordering_genes)
plot_ordering_genes(HSMM)
HSMM <- reduceDimension(HSMM, max_components = 2,
                        method = 'DDRTree')

HSMM <- orderCells(HSMM)

table(pData(HSMM)$State,pData(HSMM)$celltype)     

cds <- orderCells(HSMM, root_state = 1) 


CD4_T_OD$Pseudotime <- 
  Biobase::pData(cds)[colnames(CD4_T_OD), "Pseudotime"]

p <- plot_cell_trajectory(cds,color_by="Pseudotime") 

signature <- read.xlsx("signature.xlsx",1)
Codel     <-  na.omit(signature$Codel)

##AUC Score
exprMatrix <-  GetAssayData(CD4_T_OD, assay = "RNA", slot = "counts")
cells_AUC2 <-  AUCell_run(exprMatrix, Codel)
AUCell_auc <-  cells_AUC2@assays@data@listData[["AUC"]]
CD4_T_OD $AUC <- AUCell_auc
common_cells <- intersect(
  rownames(pData(cds)),
  colnames(CD4_T_OD)
)
Biobase::pData(cds)[common_cells, "AUC"] <- CD4_T_OD $AUC[common_cells]


##83-gene signature score along pseudotime
df <- data.frame(
  cell = rownames(Biobase::pData(cds)),
  pseudotime = Biobase::pData(cds)$Pseudotime,
  AUC = Biobase::pData(cds)$AUC,
  celltype = Biobase::pData(cds)$celltype
)


##Fig.8G(G-3)
p <- ggplot(df, aes(x = pseudotime, y = AUC)) +
  geom_point(aes(color = celltype), alpha = 0.9, size = 1)+ 
  geom_smooth(aes(group = 1), method = "loess", se = FALSE, color = "blue", size = 1) +
  scale_color_manual(values = cell_colors) +
  theme_minimal(base_size = 14) +
  theme(
    panel.border = element_rect(color = "black", fill = NA, size = 1), 
    panel.background = element_blank(),  
    plot.background = element_blank(),
    axis.ticks = element_line(color = "black", size = 0.5), 
    axis.ticks.length = unit(0.2, "cm"),
  ) +labs(
    title = "83 Gene Score",
    x = "Pseudotime",
    y = "83 Gene Score",
    color = "celltype"
  )

##Fig.8F(F-3)
df <- data.frame(
  pseudotime = pData(cds)$Pseudotime,
  celltype = pData(cds)$celltype
)

p <- ggplot(df, aes(x = pseudotime, y = celltype, fill = celltype)) +
  geom_density_ridges(scale = 1.5, alpha = 0.9, color = "white") +
  scale_fill_manual(values = cell_colors) +
  labs(x = "Pseudotime", y = "celltype", title = "") +
  theme_bw(base_size = 14) +  
  theme(
    legend.position = "none",
    panel.border = element_rect(color = "black", fill = NA, size = 1),  
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    plot.title = element_text(hjust = 0.5)  
  )


##Fig.8H(H-3)
## Monocle trajectory colored by 83-gene AUC score
p <-  plot_cell_trajectory(cds, color_by = "AUC") +
  scale_color_viridis_c() +
  ggtitle("83gene score")

saveRDS(cds,"CD4T_OD_monocle_cds.rds") 



##----------------------04CD8T GBM-----------------------------------------##

CD8_T   <- subset(T_cell, subset = celltype %in% c("CD8-Tem","CD8-Teff","CD8-Pre-Tex",
                                                   "CD8-IFN","CD8-Prolif" ))
CD8_T $celltype <- factor(
  CD8_T$celltype,
  levels = c(
    "CD8-Tem",
    "CD8-Teff",
    "CD8-Pre-Tex",
    "CD8-IFN",
    "CD8-Prolif"
  )
)
table(CD8_T$celltype)

CD8_T_GBM    <-  subset(CD8_T, subset = group == c("GBM"))

data <- GetAssayData(CD8_T_GBM, assay = "RNA", slot = "counts")
data <- as(as.matrix(data),'sparseMatrix')


pd <- new('AnnotatedDataFrame', data = CD8_T_GBM@meta.data)
fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
fd <- new('AnnotatedDataFrame', data = fData)

HSMM <- newCellDataSet(data,
                       phenoData = pd,
                       featureData = fd,
                       expressionFamily = negbinomial.size())
HSMM <- estimateSizeFactors(HSMM)
HSMM <- estimateDispersions(HSMM,cores=30)
HSMM <- detectGenes(HSMM, min_expr = 0.1 )
print(head(fData(HSMM)))

expressed_genes <- row.names(subset(fData(HSMM),
                                    num_cells_expressed >= 10))
head(pData(HSMM))


mito_genes <- grep("^MT-", rownames(HSMM), value = TRUE)
ribo_genes <- grep("^RPS|^RPL", rownames(HSMM), value = TRUE)
candidate <- setdiff(expressed_genes, c(mito_genes, ribo_genes))


diff_test_res <- differentialGeneTest(HSMM[candidate,],       
                                      fullModelFormulaStr = "~ celltype",
                                     cores = 30)

ordering_genes <- row.names (subset(diff_test_res, qval < 0.01)) 

HSMM <- setOrderingFilter(HSMM, ordering_genes)
plot_ordering_genes(HSMM)
HSMM <- reduceDimension(HSMM, max_components = 2,
                        method = 'DDRTree')

HSMM <- orderCells(HSMM)

table(pData(HSMM)$State,pData(HSMM)$celltype)     

cds <- orderCells(HSMM, root_state = 3) 

CD8_T_GBM$Pseudotime <- Biobase::pData(cds)[colnames(CD8_T_GBM), "Pseudotime"]

p <- plot_cell_trajectory(cds,color_by="Pseudotime") 

signature <- read.xlsx("signature.xlsx",1)
IDHWT     <-  na.omit(signature$IDHWT)

##AUC Score
exprMatrix <-  GetAssayData(CD8_T_GBM, assay = "RNA", slot = "counts")
cells_AUC2 <-  AUCell_run(exprMatrix, IDHWT)
AUCell_auc <-  cells_AUC2@assays@data@listData[["AUC"]]
CD8_T_GBM$AUC <- AUCell_auc
common_cells <- intersect(
  rownames(pData(cds)),
  colnames(CD8_T_GBM)
)
Biobase::pData(cds)[common_cells, "AUC"] <- CD8_T_GBM$AUC[common_cells]


##179-gene signature score along pseudotime
df <- data.frame(
  cell = rownames(Biobase::pData(cds)),
  pseudotime = Biobase::pData(cds)$Pseudotime,
  AUC = Biobase::pData(cds)$AUC,
  celltype = Biobase::pData(cds)$celltype
)


##Fig.8J(J-1)
p <- ggplot(df, aes(x = pseudotime, y = AUC)) +
  geom_point(aes(color = celltype), alpha = 0.9, size = 1)+ 
  geom_smooth(aes(group = 1), method = "loess", se = FALSE, color = "blue", size = 1) +
  scale_color_manual(values = cell_colors) +
  theme_minimal(base_size = 14) +
  theme(
    panel.border = element_rect(color = "black", fill = NA, size = 1), 
    panel.background = element_blank(),  
    plot.background = element_blank(),
    axis.ticks = element_line(color = "black", size = 0.5), 
    axis.ticks.length = unit(0.2, "cm"),
  ) +labs(
    title = "179 Gene Score",
    x = "Pseudotime",
    y = "179 Gene Score",
    color = "celltype"
  )

##Fig.8I(I-1)
df <- data.frame(
  pseudotime = pData(cds)$Pseudotime,
  celltype = pData(cds)$celltype
)

p <- ggplot(df, aes(x = pseudotime, y = celltype, fill = celltype)) +
  geom_density_ridges(scale = 1.5, alpha = 0.9, color = "white") +
  scale_fill_manual(values = cell_colors) +
  labs(x = "Pseudotime", y = "celltype", title = "") +
  theme_bw(base_size = 14) + 
  theme(
    legend.position = "none",
    panel.border = element_rect(color = "black", fill = NA, size = 1),  
    panel.grid.major = element_blank(),  
    panel.grid.minor = element_blank(), 
    plot.title = element_text(hjust = 0.5)  
  )


##Fig.8K(K-1)
## Monocle trajectory colored by 179-gene AUC score
p <-  plot_cell_trajectory(cds, color_by = "AUC") +
  scale_color_viridis_c() +
  ggtitle("179gene score")

saveRDS(cds,"CD8T_GBM_monocle_cds.rds") 


##------------------------05 CD8T Astrocytoma--------------------------##
CD8_T_Astro    <-  subset(CD8_T, subset = group == c("Astrocytoma"))

data <- GetAssayData(CD8_T_Astro, assay = "RNA", slot = "counts")
data <- as(as.matrix(data),'sparseMatrix')

pd <- new('AnnotatedDataFrame', data = CD8_T_Astro @meta.data)
fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
fd <- new('AnnotatedDataFrame', data = fData)

HSMM <- newCellDataSet(data,
                       phenoData = pd,
                       featureData = fd,
                       expressionFamily = negbinomial.size())
HSMM <- estimateSizeFactors(HSMM)
HSMM <- estimateDispersions(HSMM,cores=30)
HSMM <- detectGenes(HSMM, min_expr = 0.1 )
print(head(fData(HSMM)))

expressed_genes <- row.names(subset(fData(HSMM),
                                    num_cells_expressed >= 10))
head(pData(HSMM))


mito_genes <- grep("^MT-", rownames(HSMM), value = TRUE)
ribo_genes <- grep("^RPS|^RPL", rownames(HSMM), value = TRUE)
candidate <- setdiff(expressed_genes, c(mito_genes, ribo_genes))


diff_test_res <- differentialGeneTest(HSMM[candidate,],       
                                      fullModelFormulaStr = "~ celltype",
                                      cores = 30)

ordering_genes <- row.names (subset(diff_test_res, qval < 0.01)) 

HSMM <- setOrderingFilter(HSMM, ordering_genes)
plot_ordering_genes(HSMM)
HSMM <- reduceDimension(HSMM, max_components = 2,
                        method = 'DDRTree')
HSMM <- orderCells(HSMM)

table(pData(HSMM)$State,pData(HSMM)$celltype)     


cds <- orderCells(HSMM, root_state = 1) 

CD8_T_Astro$Pseudotime <- 
  Biobase::pData(cds)[colnames(CD8_T_Astro), "Pseudotime"]

p <- plot_cell_trajectory(cds,color_by="Pseudotime") 

signature <- read.xlsx("signature.xlsx",1)
Noncodel    <-  na.omit(signature$Noncodel)

##AUC Score
exprMatrix <-  GetAssayData(CD8_T_Astro, assay = "RNA", slot = "counts")
cells_AUC2 <-  AUCell_run(exprMatrix, Noncodel)
AUCell_auc <-  cells_AUC2@assays@data@listData[["AUC"]]
CD8_T_Astro$AUC <- AUCell_auc
common_cells <- intersect(
  rownames(pData(cds)),
  colnames(CD8_T_Astro)
)
Biobase::pData(cds)[common_cells, "AUC"] <- CD8_T_Astro$AUC[common_cells]


##30-gene signature score along pseudotime
df <- data.frame(
  cell = rownames(Biobase::pData(cds)),
  pseudotime = Biobase::pData(cds)$Pseudotime,
  AUC = Biobase::pData(cds)$AUC,
  celltype = Biobase::pData(cds)$celltype
)


##Fig.8J(J-2)
p <- ggplot(df, aes(x = pseudotime, y = AUC)) +
  geom_point(aes(color = celltype), alpha = 0.9, size = 1)+ 
  geom_smooth(aes(group = 1), method = "loess", se = FALSE, color = "blue", size = 1) +
  scale_color_manual(values = cell_colors) +
  theme_minimal(base_size = 14) +
  theme(
    panel.border = element_rect(color = "black", fill = NA, size = 1), 
    panel.background = element_blank(),  
    plot.background = element_blank(),
    axis.ticks = element_line(color = "black", size = 0.5), 
    axis.ticks.length = unit(0.2, "cm"),
  ) +labs(
    title = "30 Gene Score",
    x = "Pseudotime",
    y = "30 Gene Score",
    color = "celltype"
  )

##Fig.8I(I-2)
df <- data.frame(
  pseudotime = pData(cds)$Pseudotime,
  celltype = pData(cds)$celltype
)

p <- ggplot(df, aes(x = pseudotime, y = celltype, fill = celltype)) +
  geom_density_ridges(scale = 1.5, alpha = 0.9, color = "white") +
  scale_fill_manual(values = cell_colors) +
  labs(x = "Pseudotime", y = "celltype", title = "") +
  theme_bw(base_size = 14) + 
  theme(
    legend.position = "none",
    panel.border = element_rect(color = "black", fill = NA, size = 1), 
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),  
    plot.title = element_text(hjust = 0.5)  
  )


##Fig.8K(K-2)
## Monocle trajectory colored by 30-gene AUC score
p <-  plot_cell_trajectory(cds, color_by = "AUC") +
  scale_color_viridis_c() +
  ggtitle("30gene score")


saveRDS(cds,"CD8T_Astro_monocle_cds.rds") 


##-------------------CD8T Oligodendroglioma --------------------------##
CD8_T_OD    <-  subset(CD8_T, subset = group == c("Oligodendroglioma"))

data <- GetAssayData(CD8_T_OD, assay = "RNA", slot = "counts")
data <- as(as.matrix(data),'sparseMatrix')


pd <- new('AnnotatedDataFrame', data = CD8_T_OD@meta.data)
fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
fd <- new('AnnotatedDataFrame', data = fData)

HSMM <- newCellDataSet(data,
                       phenoData = pd,
                       featureData = fd,
                       expressionFamily = negbinomial.size())
HSMM <- estimateSizeFactors(HSMM)
HSMM <- estimateDispersions(HSMM,cores=30)
HSMM <- detectGenes(HSMM, min_expr = 0.1 )
print(head(fData(HSMM)))

expressed_genes <- row.names(subset(fData(HSMM),
                                    num_cells_expressed >= 10))
head(pData(HSMM))


mito_genes <- grep("^MT-", rownames(HSMM), value = TRUE)
ribo_genes <- grep("^RPS|^RPL", rownames(HSMM), value = TRUE)
candidate <- setdiff(expressed_genes, c(mito_genes, ribo_genes))


diff_test_res <- differentialGeneTest(HSMM[candidate,],       
                                      fullModelFormulaStr = "~ celltype",
                                      cores = 30)
ordering_genes <- row.names (subset(diff_test_res, qval < 0.01)) 


HSMM <- setOrderingFilter(HSMM, ordering_genes)
plot_ordering_genes(HSMM)
HSMM <- reduceDimension(HSMM, max_components = 2,
                        method = 'DDRTree')
HSMM <- orderCells(HSMM)

table(pData(HSMM)$State,pData(HSMM)$celltype)     
cds <- orderCells(HSMM, root_state = 3) 


CD8_T_OD$Pseudotime <- 
  Biobase::pData(cds)[colnames(CD8_T_OD), "Pseudotime"]

p <- plot_cell_trajectory(cds,color_by="Pseudotime") 

signature <- read.xlsx("signature.xlsx",1)
Codel     <-  na.omit(signature$Codel)

##AUC Score
exprMatrix <-  GetAssayData(CD8_T_OD, assay = "RNA", slot = "counts")
cells_AUC2 <-  AUCell_run(exprMatrix, Codel)
AUCell_auc <-  cells_AUC2@assays@data@listData[["AUC"]]
CD8_T_OD $AUC <- AUCell_auc
common_cells <- intersect(
  rownames(pData(cds)),
  colnames(CD8_T_OD)
)
Biobase::pData(cds)[common_cells, "AUC"] <- CD8_T_OD $AUC[common_cells]


##83-gene signature score along pseudotime
df <- data.frame(
  cell = rownames(Biobase::pData(cds)),
  pseudotime = Biobase::pData(cds)$Pseudotime,
  AUC = Biobase::pData(cds)$AUC,
  celltype = Biobase::pData(cds)$celltype
)


##Fig.8J(J-3)
p <- ggplot(df, aes(x = pseudotime, y = AUC)) +
  geom_point(aes(color = celltype), alpha = 0.9, size = 1)+ 
  geom_smooth(aes(group = 1), method = "loess", se = FALSE, color = "blue", size = 1) +
  scale_color_manual(values = cell_colors) +
  theme_minimal(base_size = 14) +
  theme(
    panel.border = element_rect(color = "black", fill = NA, size = 1), 
    panel.background = element_blank(),  
    plot.background = element_blank(),
    axis.ticks = element_line(color = "black", size = 0.5), 
    axis.ticks.length = unit(0.2, "cm"),
  ) +labs(
    title = "83 Gene Score",
    x = "Pseudotime",
    y = "83 Gene Score",
    color = "celltype"
  )

##Fig.8I(I-3)
df <- data.frame(
  pseudotime = pData(cds)$Pseudotime,
  celltype = pData(cds)$celltype
)

p <- ggplot(df, aes(x = pseudotime, y = celltype, fill = celltype)) +
  geom_density_ridges(scale = 1.5, alpha = 0.9, color = "white") +
  scale_fill_manual(values = cell_colors) +
  labs(x = "Pseudotime", y = "celltype", title = "") +
  theme_bw(base_size = 14) + 
  theme(
    legend.position = "none",
    panel.border = element_rect(color = "black", fill = NA, size = 1),  
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    plot.title = element_text(hjust = 0.5)  
  )


##Fig.8K(K-3)
## Monocle trajectory colored by 83-gene AUC score
p <-  plot_cell_trajectory(cds, color_by = "AUC") +
  scale_color_viridis_c() +
  ggtitle("83gene score")


saveRDS(cds,"CD8T_OD_monocle_cds.rds") 








